<a href="https://colab.research.google.com/github/yulianacm/Metodos-Numericos-I/blob/main/Factorizaci%C3%B3n_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Factorización LU

In [10]:
import numpy as np

In [11]:
#Matriz para usar de ejemplo
A= np.array([
    [1, 1, 0, 3],
    [2, 1, -1, 1],
    [3, -1, -1, 2],
    [-1, 2, 3, -1]
], dtype=float)

In [12]:
def factorizacionLU(A):
    n= len(A)
    L= np.zeros((n, n))
    U= np.zeros((n, n)) #Matrices L y U inicializadas en ceros

    for i in range(n):
        #Paso 4: Calcular l_ii y u_ii
        suma_diag= sum(L[i][k] * U[k][i] for k in range(i))
        L[i][i]= 1  #La diagonal principal de L es 1
        U[i][i]= A[i][i]- suma_diag
        if U[i][i]== 0:
            print("Factorización imposible, es matriz singular.")
            return None, None

        #Paso 5: Calcular u_ij y l_ji
        for j in range(i + 1, n):
            suma_u= sum(L[i][k] * U[k][j] for k in range(i))
            U[i][j]= (A[i][j] - suma_u) / L[i][i]

            suma_l= sum(L[j][k] * U[k][i] for k in range(i))
            L[j][i]= (A[j][i] - suma_l) / U[i][i]

    return L, U
L, U= factorizacionLU(A)

if L is not None and U is not None:
    print("Matriz L:")
    print(L)
    print("\nMatriz U:")
    print(U)

Matriz L:
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

Matriz U:
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
